name: Deploy To Glitch
on:
  push:
    branches:
      - master
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Glitch
        uses: kanadgupta/glitch-sync@master
        with:
          project-id: '${{ secrets.c93fca49-5d6e-47d1-9e80-676485192327 }}'
          auth-token: ''${{ secrets.41cbb373-018a-4408-a164-2a2c31589ea4 }}'